site_name: Charles Forsyth 
nav:
- Home: "index.md" 
- CV: "cv.md"
- High Performance Computing: 
  - "Intro": "hpc-home.md"
  - "Linux Basics": "hpc-linux.md"
  - "Hardware": "hpc-hardware.md"
  - "Provisioning": "hpc-provisioning.md"
  - "Architecture": "hpc-architecture.md"
  - "Schedulers": "hpc-schedulers.md"
  - "Software": "hpc-software.md"
  - "Code": "hpc-code.md"
  - "HPC in the Cloud": "hpc-aws.md"
  - "Monitoring": "hpc-monitoring.md"
  - "Metrics": "hpc-metrics.md"
- Docs:
  - "Presentations": "presentations.md"
  - "Project 2": "project2.md"
theme: flatly



