site_name: Charles Forsyth 
nav:
- Home: index.md
- High Performance Computing:
  - "HPC on AWS": "hpc-aws.md"
  - "Code": "Code.md"
  - "Presentations": "presentations.md"
- Projects:
  - "Project 1": "project1.md"
  - "Project 2": "project2.md"
theme: flatly



