site_name: Charles Forsyth 
nav:
- Home: 
  - "": "index.md"
  - "CV": "cv.md"
- High Performance Computing:
  - "HPC on AWS": "hpc-aws.md"
  - Code:
    - "Code": "Code.md"
    - "Slurm": "slurm-submission-scripts.md"
  - "Presentations": "presentations.md"
- Projects:
  - "Project 1": "project1.md"
  - "Project 2": "project2.md"
theme: flatly



